language: python
python:
- '2.7'
before_install:
- export COMMIT_SHA=`git log -1 --pretty=format:%H`
install:
- pip install -q -r requirements.txt
- npm install
script: npm run build
deploy:
- provider: s3
  access_key_id: "AKIAJVDO2NQZ5NOFDA6Q"
  secret_access_key: "$aws_secret_prod"
  bucket: ui.valence.d2l.com
  local-dir: _build/html
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
- provider: s3
  access_key_id: "AKIAJVDO2NQZ5NOFDA6Q"
  secret_access_key: "$aws_secret_internal"
  bucket: ui.edev.d2l.com
  local-dir: _build/html
  upload-dir: "${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
env:
  global:
  # GITHUB_TOKEN
  - secure: eGL/WhnF77rf0rp8g2kf6hSI1fras/gROlrnuKGgZN9sO9FO4kcuvbG5MZsnyz4CYeEFlTJ8pj5RkgokoBUwGxVAuoouUVGSVng/c+iGaDOZrEPEh7HD0K5xdodNj3330RRZi7zXyKX4stauD19x7TLipmB1trtuzWAHvJqrkMg=
  # aws_secret_internal
  - secure: GHXTbWPkSs+YSy9lsMPYrsqwkbPXnFT8t1a5FNz8gkFEoDnlIGYcH7xRYd4CM4HaSSyVzIz40ft4Tdba/IIBFTJw9zypw5xQlcBwIjPaDO4A/dNvbiJqKqYSZUGRvFS55yJJnipfQ9V5lTDRmrdchXDQU5IOHZ7to4M8r64D2s4=
  # aws_secret_prod
  - secure: fdHbL3kTf9E510NyfPQElhzdbjTpQMWldwgegcG/5Zr0EVV352YFWxuC3/q3Ct/RmCs2jqQR0w6qQ745LPz74Tm76JUoXUSb0mrB4rFAeWo1PJGxA9Tivmf0Gpt9OP/k+VwFCLjzEylkHoFJ6G9DmjtmL4vyxv5nEuxtw+D7xWk=

after_success:
- python sendComment.py "Published to http://ui.edev.d2l.com/${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}";
