language: node_js
node_js:
- 5.6
before_install:
  - rvm install 2.2.2
install:
  - gem install jekyll pygments.rb
  - npm install
script:
  - npm run build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  provider: s3
  access_key_id: AKIAI53JGZFCAU3WTR6A
  secret_access_key:
    secure: HSJWwgsMRMgwoqHjNLiWCArQajbHP6r/b9EMonne0hO4NeG3PNBlGdO9IU1zU7ehZtANGHHhTDODOxI1mBKevc29oKOr5LzgB7pnap7Dxmt353P3YIpLu6qY4/oijA5ITUFfb4OukCO1onagJJ5qKp4mPhcu7v7VqGA0cmHwiS8=
  bucket: design.d2l
  region: us-west-2
  local-dir: _site
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
