language: ruby
rvm:
- 2.1
install:
  - gem install jekyll pygments.rb
  - npm install
script:
  - npm run build
  - jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  provider: s3
  access_key_id: AKIAI53JGZFCAU3WTR6A
  secret_access_key:
    secure: ghBtEds3KA4oHq2//CclWIZMSbSJ57RoDX2pQ/s7pixWFcNCXc3vdaUWH03qZ62ADjmyNsB29gMci3SUnfXH9vUFv/hACr5+Up8DIo5brQwTtanKccnwmi619Ab1Q6V58Yyu/HIicwi2SxO5IljHYR+HyvXVv22mCn1i7uPMGLQ9xQymQSQSHm15FWpFEGWD3jfwTBU2OVz0Gd7JAQIDqEldLETogb+Cwv0cEXZcZ//ZWNSKclumD2DaQWw8e0bogbQC6hSqIODTR7IMTLTfhZ85657hI8toa0wN4DR9MDx0iWaruuUV2dOmjnVGLZwb581TmaLLgDxotwPJt21xM84fDfPKvSONhek6BCjPUEOtBIKn2WL4Eh2sLTjoXhXXEQh+ybLdp/awQlUa+CazAlcHEjYrGYCXcuY3H+CNdfsFgTMUt2hh615p3CaoOziSyXau5WIsTOa38cv+OqV2rRDJ4cFBs362BiL4wc3mL0gjRAfDCH3uvc11slqeBkcpEQbxodm2iHfzRpFf26p3izGBwfKj8fO7DvzP4cU52p9uyiw/fLA6eoyJzIS5lHLsXfUTub56SgrxYNt30R7lxCnT7v3zZQyqEzn/eLBQVN8haUpMlwEw2/VcD66hi/ZRUO0IlPtNhI8WPsEJRb3PwfuyAACrBfSMwjpu77/wEpQ=
  bucket: design.d2l
  region: us-west-2
  local-dir: _site
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
