# Site settings
title: Valence UI
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ui.valence.d2l.com" # the base hostname & protocol for your site
exclude: [node_modules, package.json]
highlighter: pygments
defaults:
  -
    values:
      layout: "page"
collections:
  components:
    output: true
  componentgroups:
    output: true
sass:
  style: :compressed
