# Site settings
title: Valence UI
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ui.valence.d2l.com" # the base hostname & protocol for your site
exclude: [README.md, vendor]
highlighter: pygments
defaults:
  -
    values:
      layout: "page"
collections:
  components:
    output: true
sass:
  style: :compressed
# Build settings
markdown: kramdown
