# -*- coding: utf-8 -*-
#
# Valence documentation build configuration file, created by
# sphinx-quickstart on Thu Oct  6 11:22:14 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

sys.path.insert(0, os.path.abspath('.extensions'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [ 'sphinx.ext.autodoc', 'sphinx.ext.extlinks', 'sphinx.ext.intersphinx', 'sphinx.ext.todo', 'sphinxcontrib.actdiag', 'sphinxcontrib.blockdiag', 'sphinxcontrib.nwdiag', 'sphinxcontrib.seqdiag', 'sphinxcontrib.phpdomain', 'd2l_local', 'd2l_htmlbuilder', 'd2l_httpdomain' ]


# Add any paths that contain templates here, relative to this directory.
templates_path = ['.templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'reference'

# General information about the project.
project = u'Valence'
copyright = u'2011-2015, Desire2Learn Incorporated. All rights reserved.'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
version = 'LSOne-003'
if tags.has("external"):
    # The short X.Y version.
    # The full version, including alpha/beta/rc tags.
    release = version
else:
    release = version + ' internal'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# do conditional building based on the -t tags passed into sphinx-build
exclude_patterns = [ '.build', '.extensions', 'external/*', '.svn', '.templates', '.themes' ]
if tags.has("external"):
    exclude_patterns = exclude_patterns + ['internal/*']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# ReST strings that the builder adds to each processed .rst file
# rst_prolog = """ """
# - note that according to a usenet newsgroup poster, this method of |term| substitution
# only works in HTML output: if we need to output to TeX, or through TeX (PDF), then
# this might be problematic
rst_epilog = """
.. include:: <isonum.txt>
"""

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = 'default'
html_theme = 'd2l'
# html_theme = 'agogo'
# html_theme = 'haiku'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# -- D2L Orange: F3901D
#    D2l Orange 75%-ish: F7B161
#    D2L Orange 50%-ish: F9C88E
#    D2L Orange 25%-ish: FDE9D2
# -- D2L Grey: 6C6F70
#    D2L Grey 75%-ish: 989A9B
#    D2L Grey 50%-ish: B6B7B8
#    D2L Grey 25%-ish: E2E2E2
#
## Default theme options
# html_theme_options = {
#    "footerbgcolor": "#6C6F70",
#    "relbarbgcolor": "#AEB0B1",
#    "sidebarbgcolor": "#F3901D",
#    "sidebartextcolor": "#FFFFFF",
#    "sidebarlinkcolor": "#FFFFFF"
#    }
## Haiku theme options
# html_theme_options = {
#     "headingcolor": "#F3901D",
#     "linkcolor": "#6C6F70",
#     "visitedlinkcolor": "#6C6F70",
#     "hoverlinkcolor": "#AEB0B1"
#     }
# html_theme_options = {
#     "bodyfont": "Calibri",
#     "headerfont": "Cambria",
#     "headerbg": "#B6B7B8",
#     "footerbg": "#6C6F70",
#     "linkcolor": "#989A9B",
#     "headercolor1": "#F3901D",
#     "headercolor2": "#F3901D",
#     "textalign": "left"
#     }

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['.themes']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#BAP html_title = project + " (" + release + ") "
html_title = project + " UI"

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['.static', 'img', 'vui-npm-modules/node_modules']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '.static/d2l-logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '.static/favicon.ico'

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'
html_last_updated_fmt = '%Y-%m-%d (%H:%M %Z)'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {
#                   'index': ['indexsidebar.html', 'search.html'],
#                   'contents': ['globaltoc.html', 'search.html'],
#                   'basic/*': ['localtoc.html', 'search.html' ],
#                   'res/*': ['localtoc.html', 'search.html'],
#                   'internal/*': ['localtoc.html', 'search.html']
#                 }

# Additional templates that should be rendered to pages, maps page names to
# template names.
html_additional_pages = {'index': 'index.html'}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If html_show_sourcelink is true, links to the reST sources are added to the pages.
if tags.has("external"):
    html_copy_source = False
else:
    html_show_sourcelink = True
    html_copy_source = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'Valencedoc'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'Valence.tex', u'Valence Documentation',
   u'Desire2Learn', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'valence', u'Valence Documentation',
     [u'Desire2Learn'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'Valence', u'Valence Documentation', u'Desire2Learn',
   'Valence', 'One line description of project.', 'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'


# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'http://docs.python.org/': None}


# -- Options for d2l-httpdomain ------------------------------------------------
D2L_httpdomain_route_mapping = {
    '/d2l/api/(D2LPRODUCT:productCode)/versions' : 'API properties',
    '/d2l/api/ext': 'API properties',
    '/d2l/api/lp/unstable/admin/routes/': 'API properties',
    '/d2l/auth' : 'API properties',
    '/d2l/lp/auth': 'API properties',
    '/d2l/api/versions' : 'API properties',
    '/d2l/api/BinderContent' : 'Binder Integration',
    '/d2l/api/lp' : 'Learning Platform',
    '/d2l/api/le' : 'Learning Environment',
    '/d2l/api/eP' : 'ePortfolio',
    '/d2l/api/lr' : 'Learning Object Repository'
    }

# default value
# http_index_ignore_prefixes = []

# -- Options for integration with sdedit ---------------------------------------
# sdedit_path = '/usr/local/bin/sdedit'

# -- Options for extlinks extension ----------------------------------------
if tags.has("external"):
    extlinks = {'extrdocs': ('/externaldocs/%s',
                             None),
                  'slides': ('/slides/%s',
                             None),
                 'pkgarch': ('/pkg-archive/%s',
                             None),
                         }
else:
    extlinks = {'extrdocs': ('/externaldocs/%s',
                             None),
                  'slides': ('/slides/%s',
                             None),
                 'pkgarch': ('/pkg-archive/%s',
                             None),
                         }


# -- Options for *diag extension -------------------------------------------
actdiag_fontpath = [ '/usr/local/lib/fonts/DejaVuSans.ttf', '/usr/local/lib/fonts/DejaVuSansMono.ttf' ]
actdiag_antialias = 'true'
blockdiag_fontpath = [ '/usr/local/lib/fonts/DejaVuSans.ttf', '/usr/local/lib/fonts/DejaVuSansMono.ttf' ]
blockdiag_antialias = 'true'
nwdiag_fontpath = [ '/usr/local/lib/fonts/DejaVuSans.ttf', '/usr/local/lib/fonts/DejaVuSansMono.ttf' ]
nwdiag_antialias = 'true'
seqdiag_fontpath = [ '/usr/local/lib/fonts/DejaVuSans.ttf', '/usr/local/lib/fonts/DejaVuSansMono.ttf' ]
seqdiag_antialias = 'true'
